version: '3.3'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    networks:
      - webproxy
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"

  nginx-proxy-letsencrypt:
    image: nginxproxy/acme-companion
    volumes:
     - acme:/etc/acme.sh
     - certs:/etc/nginx/certs
     - vhost:/etc/nginx/vhost.d
     - html:/usr/share/nginx/html
     - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
     - nginx-proxy

volumes:
  certs:
  vhost:
  html:
  acme:

networks:
  webproxy:
    external: true
